name: tutorial_coach_mark
description: Guide that helps you to present your app and its features in a beautiful, simple and customizable way. Tutorial | Guide | Coach.
version: 1.2.4
homepage: https://github.com/RafaelBarbosatec/tutorial_coach_mark

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  dart_code_metrics: ^5.4.0
  dfc_lints:
    git: https://github.com/sgehrman/dfc_lints

flutter:
